styfle/packagephobia

src/interfaces/types.d.ts
src/page-props/results.ts
src/server.ts
src/util/constants.ts

Fixes #35
/api.json?p=webpack@4.5.0

Add json api

---

README.md
now.json
src/util/badge.ts
src/util/npm-parser.ts

This new badge service should improve performance.
See [this tweet](https://twitter.com/amiocn/status/1017101016389435393) and [this tweet](https://twitter.com/amiocn/status/1017119844037058560) and [this tweet](https://twitter.com/styfle/status/1017127939626938371) for some of the differences.

Change redirect from shields to badgen

---

README.md

@styfle Turbocolor has been deprecated and succeeded by colorette. 
Cheers!

docs: mv turbocolor to its successor colorette

---

src/util/npm-api.ts

Fixes a bug where a string input with two or more forward slashes would not be escaped properly

Fix string escape

---

src/util/backend/npm-stats.ts
src/util/npm-api.ts

Fixes #137
- replace hardcoded npm registry url with one that defaults to the existing url and can be set via process.env.NPM_REGISTRY_URL.
So the only issue here is that the registry has to also be set for NPM, like in .npmrc or globally for the user on the machine. From a little digging I don't _think_ it can be set programmatically, aside from running a `npm config set` the same way the install is run. Currently I'm just using an .npmrc, when you're using your own registry you tend to have either that or the global config set up already anyway, but I'm open to suggestions to make it a little more opaque.

Allow for custom npm registries via env var

---

now.json
package-lock.json
package.json

This might not be backwards compatible so I need to do some testing.
I am also upgrading the database to be able to handle more data.
Hopefully now v2 will help with the load.

Upgrade npm to 6.x

---

README.md

I just found this tool and it appears to measure network traffic of the tarballs.

Update readme with npm-download-size tool

---

README.md

This adds the comparison of `yargs` vs `arg` to the readme.

Add yargs vs arg to readme

---

src/components/BarGraph.tsx
src/interfaces/types.d.ts
src/server.ts
src/util/badge.ts
src/util/constants.ts
src/util/npm-parser.ts

This adds a new version of the API with some additional details.
```json
{
"publishSize": 207337,
"installSize": 1612366
}
```
```json
{
"name": "express",
"version": "4.16.4",
"publish": {
"bytes": 207337,
"pretty": "202 kB",
"color": "#97CA00"
},
"install": {
"bytes": 1612366,
"pretty": "1.54 MB",
"color": "#007EC6"
}
}
```
This will provide more information for [badgen](https://github.com/amio/badgen-service) and for the [cli](https://github.com/chinanf-boy/packagephobia-cli).
/cc @amio @chinanf-boy
Fixes: #241

Add v2 api

---

now.json

We no longer need to use the canary builder and so this changes `@now/node` to use stable.

Use stable @now/node

---

now.json

The DB (redis) is hosted in the USA so no reason to deploy to all regions.
It's also causing a bunch of concurrent connections.

Change regions to USA only

---

.nowignore

Utilize the `.nowignore` file for faster deploys.
This wildcard syntax acts as an allowlist rather than an blocklist.

Change .dockerignore to .nowignore

---

package-lock.json
package.json

Reverts #350
This broke npm install with the following:
```
running npm install in /tmp...
ERROR: ENOSPC: no space left on device, mkdir '/tmp/tmp-package0.1989069454247201'
```

Revert "Bump npm from 6.10.0 to 6.10.1"

---

src/util/backend/npm-stats.ts

There was a bug where a large package like `protoss@4.0.3` would fill up the tmp storage and the never be deleted causing subsequent installs to break.

Fix ENOSPC when package fails install

---

src/components/OctocatCorner.tsx

This PR hides the octocat corner on smaller screens because it overlaps with the search button.
There is already a link to GitHub at the bottom footer so mobile can still get to the repo.

Hide octocat corner on mobile

---

src/server.ts

This assigns `HOME='/tmp'` so that `os.homedir()` returns the temporary directory which is the only writable directory.
This fixes `electron-download` and also `electron`.

Fix electron-download homedir()

---

src/server.ts

This PR will cache pages that have a query string and also the home page since the HTML response will not change for subsequent requests.

Add cdn caching for html

---

src/components/Footer.tsx

This prevents longer text from wrapping

Increase width of footer

---

.github/workflows/nodejs.yml
README.md

* specify `CI: true`
* add `fail-fast: false`
* do `npm ci` instead of `npm install` which is faster and more appropriate
* split steps
* add README.md badge
We could probably add `npm audit` later if you want @styfle

Tweak GitHub Actions CI.

---

src/components/Stats.tsx
src/interfaces/types.d.ts
src/page-props/compare.ts
src/pages/_document.ts
src/pages/compare.tsx
src/pages/index.tsx
src/pages/parse-failure.tsx
src/server.ts
src/util/constants.ts

This PR adds package comparison using commas in the search bar and the ability to upload a `package.json` from the index page. Fixes #133
This is very "minimum viable implementation" — there's definitely room for improvement, especially on the frontend of the comparison page, but I wanted to put this out there as a possibility for the implementation of the core functionality. Happy to chat about and reconsider any of the design decisions here!

Compare the sizes of multiple packages and analyze package.json

---

src/components/BarGraph.tsx
src/interfaces/types.d.ts
src/page-props/common.ts
src/page-props/results.ts
src/util/backend/npm-stats.ts
src/util/npm-api.ts
test/npm-api-test.ts

Fixes #442
@XhmikosR Since package versions are cached in redis, the date will be missing for existing packages. Is this feature worth invalidating all the data we already have on each version?

Add publish date

---

src/pages/_document.tsx

Fixes #529 
Related to https://github.com/facebook/react/pull/17878 and https://github.com/facebook/react/pull/17873

Remove React.createFactory()

---

.github/workflows/codeql.yml

Hey @styfle, long time no see!
This moves the CodeQL action to be in the right workflows directory - it should kick off CodeQL scanning once merged.

Move codeql.yml to correct workflows directory

---

README.md
src/pages/_document.tsx
src/server.ts
src/util/constants.ts

After 2+ years, it is time for a proper dot com https://packagephobia.com
We'll redirect https://packagephobia.now.sh to https://packagephobia.com for any existing links out there.

Add packagephobia.com domain name

---

vercel.json

We don't need 3GB in most cases, 1GB should do the trick.
Also redis is hosted in iad1 so we should only run the function there to reduce latency.

Change memory usage and region

---

src/util/backend/lookup.ts

Typically, npm packages are not published every second, so we can default to 30s instead of no cache which will improve perf for packages with many reads per second.

Use 30s cache default

---

src/interfaces/types.d.ts
src/page-props/common.ts
src/page-props/compare.ts
src/page-props/results.ts
src/pages/_document.tsx
src/server.ts
src/util/npm-api.ts
test/npm-api-test.ts

This PR add a dynamic `title` and `description` meta tag based on the npm manifest.
This was tricky because we used to do routing after emitting meta tags.
This PR attempts to fetch the npm manifest before any routing and then passes it to both meta tags and routing below.
Fixes #449

Add meta title and description from npm

---

src/pages/result.tsx

Follow up to #674 which is a better fix for #452. 
Thanks to @JB1905 for suggesting `position: absolute`.

Fix badge details on mobile and desktop

---

src/interfaces/types.d.ts
src/page-props/compare.ts
src/page-props/results.ts
src/pages/_document.tsx
src/pages/compare.tsx
src/pages/result.tsx
src/server.ts

This new feature allows you to filter specific versions in the chart in order to compare versions that are not chronologically adjacent.
For example, comparing each major version of TypeScript where there might be years in between.
https://packagephobia.com/result?p=typescript%400.8.1%2Ctypescript%401.0.0%2Ctypescript%402.0.2%2Ctypescript%403.0.1%2Ctypescript%404.0.2
This also fixes #684 😉

Add filtered chart feature

---

.github/workflows/nodejs.yml

https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

ci: add caching for npm

---

src/components/BarGraph.tsx

Labels for longer package versions were overlapping the bars in the chart. Fixed with `text-overflow`
- Before
- After
Closes #451

Fixed issue with label for longer package versions

---

CONTRIBUTING.md
package-lock.json
package.json
src/pages/_document.tsx
src/util/backend/db.ts

There are too many breaking changes in `redis` so we can switch to `ioredis` and get the same API.
Also switch to a single env var for the REDIS_URL so its easier to swap.
Closes #863

Switch to `ioredis` client

---

package-lock.json
package.json
src/util/npm-api.ts

We can't bump to `node-fetch@3` because it requires ESM but we still need CJS to work with `npm@6`.
Usually you can just `await import('node-fetch')` but TS doesn't work yet until it can probably support Node's ESM.
The easiest solution is to drop `node-fetch` in favor of Node.js built-in http request module.
- Closes #851 
- Closes #811

Remove `node-fetch` dependency

---

README.md

https://bundle.js.org has a new domain, namely https://bundlejs.com. I'm going around updating links anywhere bundlejs is used.

docs: update bundle.js.org to the new domain of bundlejs.com

---

src/server.ts
src/util/badge.ts

Improvement that allows to get a red badge with the message "package not found" instead of a 500 error
Fix this:

feat: return a badge when package not found

---

README.md

picocolors is the smallesst
https://packagephobia.com/result?p=chalk
https://packagephobia.com/result?p=colorette
https://packagephobia.com/result?p=kleur
https://packagephobia.com/result?p=colors
https://packagephobia.com/result?p=nanocolors
https://packagephobia.com/result?p=picocolors

chore(readme): update comparison of chalk vs picocolors

---

src/pages/index.tsx
src/server.ts
src/util/constants.ts
vercel.json

This will avoid serverless function invocations for 404s.
For example, the function logs show attackers looking for non-existing files such as:
Instead of rewriting all paths, we can rewrite only paths we know are handled by the function.

fix: 404 not found should avoid function invocation

---

package-lock.json
package.json
src/components/BarGraph.tsx
src/components/LinkedLogos.tsx
src/components/Stats.tsx
src/page-props/common.ts
src/page-props/compare.ts
src/page-props/results.ts
src/pages/_document.tsx
src/pages/compare.tsx
src/pages/result.tsx
src/server.ts
src/types.ts
src/util/backend/db.ts
src/util/backend/npm-stats.ts
src/util/badge.ts
src/util/npm-api.ts
src/util/npm-parser.ts
test/npm-api-test.ts
test/npm-parser-test.ts
test/npm-stats-test.ts
tsconfig.json

- fix types by using explicit export and import (instead of implicit global declarations)
- upgrade `typecript@5.2.2` 
- remove `test` in favor of native `node --test`

fix: upgrade `typecript@5.2.2` and fix type import

---

package-lock.json
package.json
src/page-props/common.ts
src/util/npm-api.ts

The npm registry can take 2 or more seconds to fetch a package manifest, such as https://registry.npmjs.org/next
So this PR adds `lru-cache` to avoid fetching packages that we already fetched in the past 5 min.
This is particularly useful, when clicking versions in the bar chart since the manifest should be in the lru cache already.

chore: add lru cache to improve perf

---

src/util/backend/npm-wrapper.ts

Back when Package Phobia first came out in 2018, it used `npm@5` to install dependencies and measure the size. That was later upgrade to [npm@6](https://github.com/styfle/packagephobia/pull/164) with little behavior changed.
Then upgrading node caused problems with the old version of npm so Package Phobia switched to [yarn@2](https://github.com/styfle/packagephobia/pull/959) and later [yarn@3](https://github.com/styfle/packagephobia/pull/976) which both omit peer dependencies by default.
Recently, Package Phobia switched to [npm@10](https://github.com/styfle/packagephobia/pull/1021) which will automatically install peer dependencies.
This PR will change the behavior back to omit peer dependencies.
- Fixes #1025

fix: omit peer dependencies

---

src/components/BarGraph.tsx
src/page-props/common.ts
src/page-props/results.ts
src/types.ts
src/util/backend/npm-stats.ts
src/util/npm-api.ts
test/npm-api-test.ts

fix: add accept header to npm registry req (remove publish date)

---

package-lock.json
package.json
src/util/backend/db-postgres.ts

Bumps to [`npm@10.4.0`](https://github.com/npm/cli/releases/tag/v10.4.0) which adds a fix for [arborist](https://github.com/npm/cli/pull/7126) which will avoid installing multiple libc binaries and [correctly select glibc vs musl](https://github.com/npm/rfcs/issues/438) from the optionalDependencies.

fix: bump npm@10.4.0

---

public/site.webmanifest

It seems that right now without `start_url` the PWA is not installable. This should hopefully fix the issue.

fix: add missing start_url to webmanifest

---

package-lock.json
package.json
src/page-props/results.ts

I kept npm to v10.4.0 because newer versions have some bugs like a memory leak when there's no lock file present.
Need to check if preview is fine, though.

chore: update dependencies and switch to v20 for types

---

vercel.json

This should be configured in the dashboard instead
https://vercel.com/changelog/faster-defaults-for-vercel-function-cpu-and-memory

chore(config): remove memory config

---

API.md
src/page-props/results.ts
src/server.ts

There are a lot of API requests now that Package Phobia is so popular.
We need to ensure that clients are setting a proper `user-agent` so we know where these requests are coming from and can block bad traffic.
Users who wish to call the API should add the expected user agent to [API.md](https://github.com/styfle/packagephobia/blob/main/API.md) document.

fix: add 429 rate limit for unknown user-agents

---

src/server.ts

Way too many requests coming from unknown clients. This will make sure clients identify themselves with a user-agent.

fix: more aggressive rate limit

---

API.md

Hi 👋
This PR adds [picocolors](https://github.com/alexeyraspopov/picocolors) to the list
As you can see, picocolors using API from packagephobia but get `Forbidden` error because of API block policy.
And don't worry. I set appropriate user-agent header too [here](https://github.com/alexeyraspopov/picocolors/pull/76).

docs: add new user to API.md

---

API.md

as-is : picocolors
to-be : picocolors-size-benchmark
Changed name since picocolors use API call only when size benchmark. 
Thanks!
related : https://github.com/alexeyraspopov/picocolors/pull/76

docs(API): update usename

---

src/util/backend/db-redis.ts
src/util/npm-api.ts

I was seeing warnings about duplicate labels from console.time() 
It seems it doesn't work with well with concurrency.

chore: switch console.time() to log

---

src/pages/500.tsx

- Closes https://github.com/styfle/packagephobia/issues/1063

fix: improve 500 error message

---

src/util/backend/npm-stats.ts
src/util/backend/npm-wrapper.ts

- Related to https://github.com/styfle/packagephobia/issues/1067
We give the npm package 25 seconds and that leaves 5 seconds to cleanup when we fail for a total of 30 seconds.

fix: reduce timeout to 25 seconds

---

src/pages/500.tsx

This should prevent google from trying to crawl a private link to the error logs.
The proper solution is to hide this link when the viewer is not a member of the packagephobia team since humans get confused by this too, but I am too lazy and the error page is an exception, not a happy path 🤷

fix: add `nofollow` attribute to error logs link
