styfle/packagephobia

src/components/BarGraph.tsx
src/pages/result.tsx
src/server.ts

This changes the click handler to use `<a href>` so no JS is required.

Fix click onBarClick

---

src/interfaces/types.d.ts
src/npm-api.ts
src/page-props/results.ts
src/pages/result.tsx
src/pkg-stats.ts

Show error message when package does not exist

---

src/npm-api.ts
src/page-props/results.ts

Fix for versions that do not exist

---

src/components/SearchBar.tsx
src/pages/index.tsx
src/pages/result.tsx

Add SearchBar to result page

---

src/pages/_document.ts

Add loading indicator

---

src/page-props/results.ts
src/util/npm-api.ts

Fix chart when selecting old version

---

package.json
src/pages/_document.ts
src/pages/result.tsx
src/server.ts
src/util/badge.ts
src/util/constants.ts
src/util/npm-parser.ts
test/npm-parser-test.ts
test/npm-stats-test.ts

Add /badge route

---

package-lock.json
src/util/backend/npm-stats.ts
test/a-hardlink/hardlink.txt
test/a-hardlink/original.txt
test/npm-stats-test.ts

Fix hardlinks

---

.vscode/launch.json
package-lock.json
package.json
src/util/npm-api.ts
test/npm-api-test.ts
test/npm-stats-test.ts

Fixes #37
Note that the second image no longer contains the 1.x.x line

Add sort by semver

---

src/pages/_document.ts
src/pages/about.tsx
src/server.ts
src/util/constants.ts

- Add `/robots.txt` for web crawlers
- Remove `/about` since it is not used

Add /robots.txt and remove /about page

---

package-lock.json
src/page-props/results.ts
src/pages/500.tsx
src/pages/_document.ts
src/util/backend/npm-stats.ts

Add timeout for npm install

---

src/util/backend/npm-stats.ts

Change exec to execFile

---

package-lock.json
package.json
src/pages/result.tsx

This updates all dependencies including TypeScript 3.0 🚀

Update dependencies: TS 3.0

---

.travis.yml
Dockerfile
package-lock.json

Update travis to use node 10

---

.travis.yml
package-lock.json
package.json

The build was failing again so I updated packages to latest versions

Update packages to latest and change travis build to use docker

---

src/components/LinkedLogos.tsx

Fix encoded link to npm.anvaka.com

---

README.md
src/components/Footer.tsx

Revise description

---

src/components/SearchBar.tsx

Testing autocomplete="off" to see if it fixes the Back button https://stackoverflow.com/a/28741481/266535

Add autocomplete=off

---

src/components/LinkedLogos.tsx
src/interfaces/types.d.ts
src/page-props/results.ts
src/pages/result.tsx

Add flag isLatest to remove version from querystring

---

CONTRIBUTING.md
Dockerfile

@dependabot-bot still doesn't know how to upgrade multi-stage Dockerfiles 😢 
This makes sure the build stage and the run stage use the same version of node: 10.11.0 👍

Upgrade node to 10.11.0

---

Dockerfile

Bump Dockerfile node to 10.13.0

---

src/interfaces/types.d.ts
src/page-props/results.ts
src/util/npm-api.ts
test/npm-api-test.ts

Add support for dist-tags

---

Dockerfile

Bump node to 10.14.0

---

now.json
package-lock.json
package.json
src/components/BarGraph.tsx
src/page-props/results.ts
src/pages/_document.ts
src/server.ts
src/util/backend/npm-stats.ts
src/util/backend/npm-wrapper.ts

This is my first attempt to get Package Phobia running on Now v2

Upgrade to now v2

---

src/interfaces/types.d.ts
src/server.ts

This is a follow up to #266 since I forgot to push (oops) 😖 
@chinanf-boy will benefit from getting the name and version in the packagephobia-cli

Add version and name to api v2

---

src/pages/result.tsx
src/server.ts
src/util/badge.ts

Fixes #241
I'll merge & deploy this once @amio deploys badgen 🚀

Add redirect to badgen.net proper

---

src/components/Footer.tsx
src/components/SearchBar.tsx
src/pages/index.tsx

Improve a11y

---

src/util/backend/lookup.ts

Make sure the CDN caches response

Add s-maxage cache-control

---

now.json
package.json

Use `@now/node@canary` and Node `10.x`

---

.travis.yml

Use node 10 for unit tests

---

README.md

This tool looks similar but its static data only and the author hasn't updated it an awhile.

Add http://pkgsize.com to readme

---

src/pages/_document.ts
src/server.ts

Ran prettier.

---

src/pages/_document.ts

* use lowercase `doctype`
* move meta and title higher
* remove unneeded HTML end tags
* remove the unneeded type from `script`

Minor HTML tweaks.

---

now.json

Bump memory to 3GB

---

package.json

Also quote the tape globs.
I did this so that one can easily run the individual scripts alone.

package.json: mark it as private and quote the tape globs

---

now.json

Add security headers

---

src/util/npm-parser.ts
test/npm-parser-test.ts

Trim package name whitespace

---

package.json

This bumps to Node 12 LTS
I also removed unnecessary package.json fields.

Use node 12

---

src/components/LinkedLogos.tsx

Before: https://npm.anvaka.com/#/view/2d/httpstat
After: https://npm.anvaka.com/#!/view/2d/httpstat

Fix link to npm.anvaka.com

---

src/pages/_document.ts

Fixes #443 using [preconnect](https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect).

Add preconnect meta tag

---

README.md

Add sponsor badge

---

README.md

This badge will help determine if something is wrong with Package Phobia by monitoring uptime with https://uptimerobot.com

Add badge for uptime

---

.github/workflows/nodejs.yml
package-lock.json
package.json
src/pages/_document.ts

This will run prettier formatting for each commit so that we never get out of sync.
CI will also catch PRs that are not formatted properly with a lint script.

Add git precommit hook for prettier

---

src/components/Ad.tsx
src/components/CodeFundAd.tsx
src/pages/_document.ts
src/pages/index.tsx

Add codefund ad

---

now.json

Trying out the new configuration

Switch to headers/rewrites

---

src/pages/result.tsx

Ad on result page

---

src/pages/_document.ts

Fix ad placement

---

CONTRIBUTING.md
src/components/Footer.tsx

https://vercel.com/blog/zeit-is-now-vercel

Rename ZEIT Now to Vercel

---

README.md
src/components/Footer.tsx

Use my new personal website at https://styfle.dev

Rename ceriously to styfle

---

src/components/Stats.tsx
src/pages/compare.tsx
src/server.ts

Update compare page

---

src/server.ts
src/util/backend/db.ts

Delete global env vars after reading

---

src/components/CarbonAd.tsx
src/pages/compare.tsx
src/pages/index.tsx
src/pages/result.tsx

Ethical Ads isn't ready to serve content yet so changing to Carbon Ads to try it out
Related to #461

Change EthicalAd to CarbonAd

---

src/pages/compare.tsx
src/pages/index.tsx
src/pages/result.tsx

Reverts #602 since CarbonAds pays less than $1 per month and I can see EthicalAds is starting to work now.
Closes #623.

Change CarbonAd back to EthicalAd

---

package-lock.json
package.json
src/util/backend/npm-wrapper.ts

Bump typescript from 4.0.5 to 4.1.2 

---

package-lock.json
package.json
src/pages/_document.tsx
src/server.ts
src/util/badge.ts

Add badgen as dependency

---

src/pages/result.tsx
src/util/badge.ts

This prevents the image from jumping after loading

Fix CLS by using inline SVG

---

src/pages/result.tsx

Fix badge details on mobile

---

API.md
README.md

Hi, I really like this project. However, I noticed there isn't any API documentation, so I made some.
After seeing #141, I thought that a little disclaimer would be nice as well, so I added that too.

Add simple API documentation

---

src/util/backend/db.ts

```ts
import { createClient } from 'redis';
console.log('Connecting to source...')
const srcClient = createClient({
host: process.env.HOST1
port: process.env.PORT1,
password: PROCESS.env.PASSWORD1
}).on('error', err => {
console.error('Redis source client error: ', err);
});
console.log('Connecting to destination...')
const destClient = createClient({
host: process.env.HOST2
port: process.env.PORT2,
password: PROCESS.env.PASSWORD2
tls: true,
}).on('error', err => {
console.error('Redis destination client error: ', err);
});
console.log('Fetching from source...')
srcClient.keys('*', (err, keys) => {
if (err) throw err;
let i = 0;
for (let key of keys) {
srcClient.hgetall(key, (err2, hash) => {
if (err2) throw err2;
for (var [version, payload] of Object.entries(hash)) {
destClient.hset(key, …
```

Move to upstash redis, enable tls

---

package-lock.json
package.json

Node.js 14 and regenerate lock file

Use Node.js 14

---

.github/workflows/codeql.yml

Fix double CodeQL

---

package-lock.json
package.json

@zeit/git-hooks => @vercel/git-hooks

Deps: Update @vercel/git-hooks

---

src/pages/_document.tsx

Example: https://packagephobia.com/result?p=%40surgio%2Fgateway

Fix: escape html title/desc

---

src/page-props/results.ts

Fix tag resolution

---

package-lock.json
package.json
src/pages/_document.tsx

Bump typescript to 4.4.2

---

.github/workflows/nodejs.yml

* update to `actions/setup-node@v2`; now cache: npm works
* specify `FORCE_COLOR: 2` for colored output
* reindent

Update CI config

---

src/util/npm-api.ts

Fix npm manifest shape

---

src/components/BarGraph.tsx

Reverts styfle/packagephobia#844
Due to https://github.com/styfle/packagephobia/pull/844#issuecomment-963546105

Revert "Fixed issue with label for longer package versions"

---

src/server.ts

Reported by [Felix Mosheev](https://twitter.com/felix_mosheev)

Delete AWS env vars

---

package-lock.json
package.json
src/util/backend/db.ts

Bump ioredis 5

---

package-lock.json
package.json
src/components/PageContainer.tsx

chore: bump @types/react@18.0.8

---

package-lock.json
package.json
test/npm-api-test.ts
test/npm-parser-test.ts
test/npm-stats-test.ts

See https://github.com/nodejs/node-core-test

Switch from `tape` to `test`

---

package.json
yarn.lock

Bump ioredis 5.1.0

---

src/page-props/results.ts
src/pages/404.tsx
src/pages/_document.tsx
src/util/not-found-error.ts
src/util/npm-api.ts

Improve error when package not found

---

.github/workflows/nodejs.yml

- Fix ci to use correct node version
- Remove unused cache

Fix ci node version

---

README.md

https://twitter.com/styfle/status/1619058702753071105

Update readme to mention typescript@5.0.0-beta

---

package.json
src/util/backend/npm-stats.ts
yarn.lock

https://prettier.io/blog/2023/07/05/3.0.0.html

chore(deps): bump prettier@3.0.0

---

README.md

Adding this similar tool the readme. See tweet from @privatenumber with more details:
https://twitter.com/privatenumbr/status/1681206731127554048

chore: update README.md with pkg-size.dev

---

src/util/backend/db-postgres.ts
src/util/backend/db-redis.ts

chore: log timing for `insert()`

---

API.md

Hi :wave:
This PR adds https://socket.dev to the list

docs: update API users

---

src/components/LinkedLogos.tsx

- https://github.com/npmgraph/npmgraph/issues/132

feat: add sizing to query string of npmgraph

---

.github/workflows/dependabot.yml

chore(ci): add dependabot

---

public/robots.txt

block bad bots using up bandwidth for no reason

fix: update robots.txt

---

src/util/backend/lookup.ts

Suggested in https://github.com/styfle/packagephobia/pull/1051#issuecomment-2219321818

fix: change default cache max-age=60

---

src/server.ts

fix: more aggressive rate limit

---

src/server.ts

Increase the `cache-control` header from 7 days to 31 days

fix: bump cache from 7d to 31d

---

package-lock.json
package.json

chore: change node and npm version

---

src/components/PageContainer.tsx

https://news.ycombinator.com/item?id=43419462

fix: 100vh => 80vh

---

API.md

chore: update api.md docs
